// List of all quizzes and where their config files live
const QUIZZES = [
  {
    id: "1510",
    name: "COMP 1510",
    folderName: "java",
    chaptersFile: "./questiondata/chapters/javaChapters.json",
    exams: ["Midterms", "Finals"],
    midtermCount: 6,
    finalCount: 8,
  },
  {
    id: "1537",
    name: "COMP 1537",
    folderName: "web",
    chaptersFile: "./questiondata/chapters/webChapters.json",
    exams: ["Midterms", "Finals"],
    midtermBank: "./questiondata/chapters/web/webMidterm.json",
    finalBank: "./questiondata/chapters/web/webFinal.json",
    chapterFilenames: {
      1: "html.json",
      2: "css.json",
      3: "javascript.json",
      4: "sql.json",
      5: "dom.json",
      6: "ajax.json",
      7: "nodejs.json",
      8: "crud.json",
    },
  },
  {
    id: "1712",
    name: "COMP 1712",
    exams: [""],
    midtermBank: "./questiondata/chapters/webMidterm.json",
    finalBank: "./questiondata/webFinal.json",
  },
  {
    id: "2537",
    name: "COMP 1510",
    folderName: "web2",
    chaptersFile: "./questiondata/chapters/web2Chapters.json",
    exams: ["Quiz 1", "Quiz 2", "Quiz 3", "Quiz 4"],
    examBanks: {
      "Quiz 1": "./questiondata/chapters/web2/quiz1.json",
      "Quiz 2": "./questiondata/chapters/web2/quiz2.json",
      "Quiz 3": "./questiondata/chapters/web2/quiz3.json",
      "Quiz 4": "./questiondata/chapters/web2/quiz4.json",
    },
    answerBanks: {
      "Quiz 1": "./questiondata/answers/web2/quiz1Answers.json",
      "Quiz 2": "./questiondata/answers/web2/quiz2Answers.json",
      "Quiz 3": "./questiondata/answers/web2/quiz3Answers.json",
      "Quiz 4": "./questiondata/answers/web2/quiz4Answers.json",
    },
    chapterFilenames: {
      1: "week1.json",
      2: "week2.json",
      3: "week3.json",
      4: "week4.json",
    },
  },
  {
    id: "term",
    name: "placeholder",
    exams: [""],
    midtermBank: "./questiondata/chapters/webMidterm.json",
    finalBank: "./questiondata/webFinal.json",
  },
  {
    id: "2121",
    name: "COMP 2121",
    folderName: "dscmath",
    chaptersFile: "./questiondata/chapters/dscMathChapters.json",
    exams: ["Midterms", "Finals"],
    midtermCount: 3,
    finalCount: 6,
    chapterFilenames: {
      1: "dscMathCH01.json",
      2: "dscMathCH02.json",
      3: "dscMathCH03.json",
      4: "dscMathCH04.json",
      5: "dscMathCH05.json",
      6: "dscMathCH06.json",
    },
  },
  {
    id: "2510",
    name: "COMP 2510",
    folderName: "dscmath",
    chaptersFile: "./questiondata/chapters/dscMathChapters.json",
    exams: ["Midterms", "Finals"],
    midtermCount: 3,
    finalCount: 6,
    chapterFilenames: {
      1: "dscMathCH01.json",
      2: "dscMathCH02.json",
      3: "dscMathCH03.json",
      4: "dscMathCH04.json",
      5: "dscMathCH05.json",
      6: "dscMathCH06.json",
    },
  },
  {
    id: "2522",
    name: "COMP 2522",
    folderName: "dscmath",
    chaptersFile: "./questiondata/chapters/dscMathChapters.json",
    exams: ["Midterms", "Finals"],
    midtermCount: 3,
    finalCount: 6,
    chapterFilenames: {
      1: "dscMathCH01.json",
      2: "dscMathCH02.json",
      3: "dscMathCH03.json",
      4: "dscMathCH04.json",
      5: "dscMathCH05.json",
      6: "dscMathCH06.json",
    },
  },
  {
    id: "2714",
    name: "COMP 2714",
    exams: [""],
    midtermBank: "./questiondata/chapters/webMidterm.json",
    finalBank: "./questiondata/webFinal.json",
  },
  {
    id: "2721",
    name: "COMP 2721",
    folderName: "compArch",
    chaptersFile: "./questiondata/chapters/compArchChapters.json",
    exams: ["Midterms", "Finals"],
    midtermCount: 4,
    finalCount: 8,
    chapterFilenames: {
      1: "compArchCH01.json",
      2: "compArchCH02.json",
      3: "compArchCH03.json",
      4: "compArchCH04.json",
      5: "compArchCH05.json",
      6: "compArchCH06.json",
      7: "compArchCH07.json",
      8: "compArchCH08.json",
    },
  },
];
